// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCsMDoRxCxcOho74DDhnGUUDS3cp0Mc_M',
    appId: '1:307130120473:web:11f096014d7bd44dad2d88',
    messagingSenderId: '307130120473',
    projectId: 'verificasoftware-25da3',
    authDomain: 'verificasoftware-25da3.firebaseapp.com',
    storageBucket: 'verificasoftware-25da3.appspot.com',
    measurementId: 'G-5QKEP96SDT',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSmKjjJZ4kqyftaDkwcg0j_wXCuoeENCY',
    appId: '1:307130120473:ios:3e4e43b6e011ca25ad2d88',
    messagingSenderId: '307130120473',
    projectId: 'verificasoftware-25da3',
    storageBucket: 'verificasoftware-25da3.appspot.com',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCsMDoRxCxcOho74DDhnGUUDS3cp0Mc_M',
    appId: '1:307130120473:web:38ddbf71705e6634ad2d88',
    messagingSenderId: '307130120473',
    projectId: 'verificasoftware-25da3',
    authDomain: 'verificasoftware-25da3.firebaseapp.com',
    storageBucket: 'verificasoftware-25da3.appspot.com',
    measurementId: 'G-MK2Z6B3NC3',
  );
}
